#!/usr/bin/env ruby
site 'http://community.opscode.com/api/v1'
#site 'https://supermarket.chef.io/users/sous-chefs'
#site 'https://supermarket.chef.io'

cookbook 'runit'
cookbook 'apt'
cookbook 'ohai'
cookbook 'build-essential'
cookbook 'pcre'
cookbook 'openssl-source'
cookbook 'nginx'
cookbook 'haproxy'
cookbook 'iptables'
cookbook 'sshd'
cookbook 'ssh-hardening'
cookbook 'iptables'


